name = "zippy_magenta_canidae-48ff"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "zippy_magenta_canidae-48ff_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "zippy_magenta_canidae-48ff.wasm"
command = "npm run build:release"
